# Configuration for pr-labeller actions

'Mod: HowTo 📰': src/pages/Howto/**/*
'Mod: Events 🎉': src/pages/Events/**/*
'Mod: Maps 🗺': src/pages/Maps/**/*

'backend': functions/**/*

'Documentation':
  - any: ['README.md', 'documentation/**/*']

'Mod: DevOps 🤖':
  - any: ['cypress/**/*', 'scripts/**/*']
