language: node_js
node_js:
  - '10'
dist: trusty
sudo: false
cache: yarn
addons:
  chrome: stable

env:
  # Tell jest to run without non-interactive mode
  CI=true

# add the current github branch as an environment variable
before_script:
  - export REACT_APP_BRANCH=$TRAVIS_BRANCH
  - echo "REACT_APP_BRANCH=$REACT_APP_BRANCH"
script:
  - yarn cy:test:record
