language: node_js
node_js:
  - '10'
dist: trusty
cache:
  # cache both yarn (.cache) and npm (for global installs)
  yarn: true
  directories:
    - ~/.cache
    - ~/.npm
addons:
  chrome: stable
  firefox: latest
  apt:
    packages:
      # Required for cypress parallel tests
      - libgconf-2-4
branches:
  only:
    - master
    - production
env:
  # cy - use firefox in headless mode for CI
  - global:
      - DEBUG=True
      - MOZ_HEADLESS=1
install:
  - yarn install --frozen-lockfile --silent
# add the current github branch as an environment variable
before_script:
  - echo "MATRIX=$MATRIX_VAR"
  - export REACT_APP_BRANCH=$TRAVIS_BRANCH
  - echo "REACT_APP_BRANCH=$REACT_APP_BRANCH"

###############################################################################################################
# E2E Tests (cypress)
###############################################################################################################
# create a default script to be triggered from jobs
# see https://docs.travis-ci.com/user/build-matrix/#job-uniqueness-and-duplicate-jobs
defaults: &defaults
  script:
    - echo "group=$CI_GROUP browser=$CI_BROWSER"
    - export TZ=UTC
    # A bit ugly to look at, but this starts the platform server with ci environment variables,
    # waits until it's fully responsive, and then executes cypress tests for a given browser and parallel node
    # see https://docs.cypress.io/guides/guides/parallelization.html
    - npm run test ci
    # to kill all background jobs (like "npm start &")
    - kill $(jobs -p) || true
# Jobs run in parallel, so split chrome and firefox tests running each across 2 machines.
# CI_NODE var just ensures job env unique (otherwise won't run), others are passed to default script
jobs:
  include:
    - stage: test
      env:
        - CI_GROUP=2x-chrome
        - CI_BROWSER=chrome
        - CI_NODE=0
      <<: *defaults
    - stage: test
      env:
        - CI_GROUP=2x-chrome
        - CI_BROWSER=chrome
        - CI_NODE=1
      <<: *defaults
    - stage: test
      env:
        - CI_GROUP=2x-firefox
        - CI_BROWSER=firefox
        - CI_NODE=0
      <<: *defaults
    - stage: test
      env:
        - CI_GROUP=2x-firefox
        - CI_BROWSER=firefox
        - CI_NODE=1
      <<: *defaults
###############################################################################################################
# Deployment (firebase)
###############################################################################################################
# install firebase cli and set firebase project ci token from environment
before_deploy:
  - npm run build
  - npm install -g firebase-tools
  - export FIREBASE_TOKEN=$(if [ "$TRAVIS_BRANCH" == "production" ]; then echo "$FIREBASE_PRODUCTION_TOKEN"; else echo "$FIREBASE_STAGING_TOKEN"; fi)
deploy:
  - provider: script
    script: bash scripts/deploy.dev.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy.prod.sh
    skip_cleanup: true
    on:
      branch: production
after_deploy:
  - echo "REACT_APP_BRANCH=$REACT_APP_BRANCH"
