language: node_js
node_js:
  - '10'
dist: trusty
cache:
  # cache both yarn (.cache) and npm (for global installs)
  yarn: true
  directories:
    - ~/.cache
    - ~/.npm
addons:
  chrome: stable
  firefox: latest
  apt:
    packages:
      # Required for cypress parallel tests
      - libgconf-2-4
branches:
  only:
    - master
    - production
env:
  # cy - use firefox in headless mode for CI
  - global:
      - DEBUG=True
      - MOZ_HEADLESS=1
      - MATRIX_VAR=1
      - MATRIX_VAR=2
install:
  - yarn install --frozen-lockfile --silent
# add the current github branch as an environment variable
before_script:
  - echo "MATRIX=$MATRIX_VAR"
  - export REACT_APP_BRANCH=$TRAVIS_BRANCH
  - echo "REACT_APP_BRANCH=$REACT_APP_BRANCH"

##############################################################################
# Cypress E2E Tests (parallel)
# create a default script that will allow cypress tests to be triggered from
# jobs (which creates a parallel travis matrix that cypress can hook into)
# Note - depending on server load these may/may not always actually run in parallel
defaults: &defaults
  script:
    - echo "group=$STAGE_NAME browser=$STAGE_BROWSER"
    # A bit ugly to look at, but this starts the platform server with ci environment variables,
    # waits until it's fully responsive, and then executes cypress tests for a given browser and parallel node
    - start-server-and-test start:ci http-get://localhost:3456 "$(npm bin)/cypress run --record --key=62585f33-d688-47b7-acb3-6d1dca832065 --parallel --browser $STAGE_BROWSER --group $STAGE_NAME --ci-build-id $TRAVIS_BUILD_ID"
    # to kill all background jobs (like "npm start &")
    - kill $(jobs -p) || true

jobs:
  include:
    # set chrome and firefox tests to run in parallel (single machine, 4 threads)
    - stage: test
      env:
        - STAGE_NAME=2x-chrome-a
        - STAGE_BROWSER=chrome
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME=2x-chrome-a
        - STAGE_BROWSER=chrome
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME=2x-chrome-b
        - STAGE_BROWSER=chrome
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME=2x-chrome-b
        - STAGE_BROWSER=chrome
      <<: *defaults
##############################################################################

# install firebase cli and set firebase project ci token from environment
before_deploy:
  - npm run build
  - npm install -g firebase-tools
  - export FIREBASE_TOKEN=$(if [ "$TRAVIS_BRANCH" == "production" ]; then echo "$FIREBASE_PRODUCTION_TOKEN"; else echo "$FIREBASE_STAGING_TOKEN"; fi)
deploy:
  - provider: script
    script: bash scripts/deploy.dev.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy.prod.sh
    skip_cleanup: true
    on:
      branch: production
after_deploy:
  - echo "REACT_APP_BRANCH=$REACT_APP_BRANCH"
