# Create and deploy a build on all pull requests
name: PR Preview
on:
  # use pull_request_target so that secrets accessible from fork
  pull_request_target:
    # Trigger when labels are changed or more commits added to a PR that contains labels
    types: [labeled, synchronize]
    # Only create a preview if changes have been made to the main src code or backend functions
    paths:
      - 'src/**'
      - 'functions/**'
jobs:
  build_and_preview:
    # NOTE - as we are going to check out and build from forks we also need to add manual
    # check that malicious code has not been inserted. This is handled by manually labelling the PR
    # https://securitylab.github.com/research/github-actions-preventing-pwn-requests
    if: contains(github.event.pull_request.labels.*.name, 'Review allow-preview ✅')
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          # pull the repo from the pull request source, not the default local repo
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install npm dependencies
        run: yarn install
      - name: Build for Preview
        run: npm run build
        env:
          # currently some linting fails when CI mode enabled (warnings become errors)
          # disable until fully resolved
          CI: false
          # specify the 'preview' site variant to populate the relevant firebase config
          REACT_APP_SITE_VARIANT: preview
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          # the details of the service account need to be populated to github secrets
          # these must match the target projectId account
          firebaseServiceAccount: '${{ secrets.ONEARMY_NEXT_FIREBASE_SERVICE_ACCOUNT }}'
          expires: 30d
          projectId: onearmy-next
